### PR TITLE
Setup project

### PR DESCRIPTION
**Pull request by fenix56**
1) MVVM-C architecture files added:
- AppCoordinator,
- NewsModel,
- NewsFeedViewModel,
- NewsFeedViewController,
2) Networking/NetworkManager created,
3) Storyboard file removed from project and plist file references.

Project structure rearranged:
Screenshot 2022-09-17 at 13 16 01

### CODE REVIEW

**Comment by Meendex** [comment]
Looks good, the app structure adheres to MVVMc architecture.
Why was original storyboard removed and replaced with the new one?

**Comment by fenix56** [comment]
Where do you see new storyboard?

**Review by Meendex — APPROVED** [review]
Looks good, the app structure adheres to MVVMc architecture.
Why was original storyboard removed and replaced with the new one?

**Review by fenix56 — COMMENTED** [review]
All good

**Pull request merged**
